[project]
name = "docker-practise"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rohin", email = "rohin.kotagiri@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
docker-practise = "docker_practise:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
